import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReduxProvider } from "@/redux/Provider";
import "./globals.css";
import ToastProvider from "@/utils/toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} !bg-none`}><ReduxProvider>
        {children}
        <ToastProvider />
      </ReduxProvider></body>
    </html>
  );
}
